paths:
  # out_folder: "/data/yuansheng/eval/gpt-4o/matplotlib" # for output files
  out_folder: "/data/yuansheng/eval/qwen2_5_7b_coder_stage1_lr5e6_20K/seaborn/epoch2" # for output files
  dataset_folder: "dataset"
  results_filename: "results.json" # json stores temporarily plotting responses. Located in the out_folder
  bench_stat_filename: "benchmark_stat.jsonl" # json stores final statistics of the benchmark results. Located in the out_folder
  # instructs_file: "instructs/instructs.json" # Optional. Default instructs exists. json stores instructs for plot generation and LLM-benchmarking.
benchmark_types: ["vis", "task"] # Options: "vis", "task", "codebert"
plotting_lib: "seaborn" # "matplotlib", "seaborn", "plotly", "lets-plot" (does not work)
data_descriptor: "head" # data descriptor. Options: "pycharm", "datalore", "lida", "head", "describe", "empty"
model_plot_gen:
  # names: ["openai/gpt-4o"] # Models to benchmark
  # names: ["Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen2.5-Coder-7B-Instruct", "meta-llama/Llama-3.1-8B-Instruct"]

  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr1e5/v0-20250419-072455/checkpoint-437"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr1e5/v0-20250419-072455/checkpoint-874"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr1e5/v0-20250419-072455/checkpoint-1311"]

  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6/v0-20250419-230656/checkpoint-1748"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6/v0-20250419-230656/checkpoint-3496"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6/v0-20250419-230656/checkpoint-5241"]

  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6_55K/v0-20250420-074313/checkpoint-1719"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6_55K/v0-20250420-074313/checkpoint-3438"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6_55K/v0-20250420-074313/checkpoint-5157"]

  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6_20K/v0-20250421-031544/checkpoint-313"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6_20K/v0-20250421-031544/checkpoint-626"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_stage1_lr5e6_20K/v0-20250421-031544/checkpoint-936"]

  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_coder_stage1_lr5e6_55K/v0-20250420-230521/checkpoint-430"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_coder_stage1_lr5e6_55K/v0-20250420-230521/checkpoint-860"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_coder_stage1_lr5e6_55K/v0-20250420-230521/checkpoint-1290"]

  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_coder_stage1_lr5e6_20K/v1-20250421-070642/checkpoint-157"]
  names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_coder_stage1_lr5e6_20K/v1-20250421-070642/checkpoint-314"]
  # names: ["/data/yuansheng/ms-swift/output/qwen2_5_7b_coder_stage1_lr5e6_20K/v1-20250421-070642/checkpoint-468"]
  # Example of names:
  # names: ["together/meta-llama/Llama-3.2-3B-Instruct-Turbo", "meta-llama/Llama-3.2-1B-Instruct", "openai/gpt-4o-2024-05-13"]
  parameters: # List of additional model parameters.
    temperature: 0.0
model_judge:
  name: "openai/gpt-4o-2024-05-13"
  parameters: # List of additional model parameters.
    temperature: 0.0